/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import br.com.model.Funcionario;
import br.com.model.controller.FuncionarioController;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author guest01
 */
public class JanelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form JanelaLogin
     */
    public JanelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txUsuario = new javax.swing.JTextField();
        txSenha = new javax.swing.JTextField();
        btAcessar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(372, 465));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Usuario: ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 210, 100, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Senha:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 260, 90, 22);
        jPanel1.add(txUsuario);
        txUsuario.setBounds(100, 210, 220, 40);

        txSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txSenhaKeyPressed(evt);
            }
        });
        jPanel1.add(txSenha);
        txSenha.setBounds(100, 260, 220, 40);

        btAcessar.setText("Acessar");
        btAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcessarActionPerformed(evt);
            }
        });
        btAcessar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btAcessarKeyPressed(evt);
            }
        });
        jPanel1.add(btAcessar);
        btAcessar.setBounds(100, 320, 110, 23);

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        jPanel1.add(btSair);
        btSair.setBounds(220, 320, 100, 23);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/washing.jpg"))); // NOI18N
        Fundo.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel1.add(Fundo);
        Fundo.setBounds(0, 0, 370, 430);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 370, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcessarActionPerformed
        // TODO add your handling code here:
        validaLogin();
    }//GEN-LAST:event_btAcessarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void txSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
           
            validaLogin();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            System.exit(0);
        }
    }//GEN-LAST:event_txSenhaKeyPressed

    private void btAcessarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btAcessarKeyPressed
//        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//            validarLogin();
//        }
    }//GEN-LAST:event_btAcessarKeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JButton btAcessar;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txSenha;
    private javax.swing.JTextField txUsuario;
    // End of variables declaration//GEN-END:variables

    private void validaLogin() {
        
        boolean autenticar = false;
        JanelaPrincipal jp = new JanelaPrincipal();
        FuncionarioController fc = new FuncionarioController();
        
        String login = txUsuario.getText();
        
        String senha = txSenha.getText();
        
        autenticar = fc.validaLogin(login, senha);
        
        if(autenticar == true){
            JOptionPane.showMessageDialog(null, "Login efetuado com sucesso.");
            jp.setLocationRelativeTo(null);
            jp.setExtendedState(jp.MAXIMIZED_BOTH);
            jp.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "login ou senha incorretos");
        }
    }
}
